name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # trigger on push to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./quasar-project

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: quasar-project/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npx quasar build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./quasar-project/dist/spa
          publish_branch: gh-pages
          cname: sirantoinek.com
          enable_jekyll: false